
server:
  port: 2023

spring:
  jpa:
    database: default
  datasource:
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MySQL-PASSWORD}
    url: jdbc:mysql://localhost:3306/weather


retrofit:
  integration:
    cacheSizeInMb: 50
    cacheDirectory: "retrofit/cache"
    longRunningReadTimeout: 300
  endpoints:
    - serviceName: currentWeather
      baseUrl: http://localhost:2122/
      path: weather
    - serviceName: hourlyWeather
      baseUrl: http://localhost:2122/
      path: weather/hourly
    - serviceName: dailyWeather
      baseUrl: http://localhost:2122/
      path: weather/daily
    - serviceName: ipApi
      baseUrl: http://ip-api.com/json/
